### ISSUE TITLE
add check if the element already has change layout??

### ISSUE THREAD

**Issue by nitronapp** [codrops/PFold#1]
Hi, I'm using PFold in a loop with infinitscroll plugin, infinitscroll does not pull any scripts from the header or anywhere when rendering new elements,so i was forced to load PFold via infinitscroll, but that will keep reloading PFold each time new elements are loaded so the script adds "div class="uc-final-wrapper" to old elements that already has it from the previous load of PFold .

what i want is to add a check in PFold so if the element already has the "div class="uc-final-wrapper"  it wont add another one to it. in other words add "div class="uc-final-wrapper" only to new elements that don't have it. if you want I'll pay for this small add in your code.

Many Thanks!

**Comment by botelho** [comment]
No need for payment.
I am just not sure if I am understanding correctly. Also, could you make sure the code is not being stripped away. I think there's something missing in your previous message, right?
BTW, I am closing it because it's not an issue. Please contact me directly at info@tympanus.net
Cheers
